[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"

[lint]
exclude_lints = ["unaliased-plain-import"]
